### ISSUE TITLE
PHP 7.3 compatibility issues: Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by kenkataiwa** [zendframework/zend-stdlib#97]
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\<path>vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 426

**Comment by Xerkus** [comment]
This compatibility issue is fixed in zend-stdlib 3.2.1(See CHANGELOG). You need to update your dependencies.

**Comment by kenkataiwa** [comment]
I'm using ZF2 (not ZF3) and I think it's still a problem, please see below:

Installation request for zendframework/zend-stdlib ^3 -> satisfiable by zendframework/zend-stdlib[3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.3.x-dev, 3.2.x-dev].
zendframework/zendframework 2.5.2 requires zendframework/zend-stdlib ~2.5.0 -> satisfiable by zendframework/zend-stdlib[2.5.0, 2.5.1, 2.5.2]

**Comment by Xerkus** [comment]
The v2 series is no longer supported (see the [LTS page for details](https://framework.zend.com/long-term-support)).
